#!/usr/bin/env sh
    set -eu
    echo "Eliminando todos los archivos de ${WORKSPACE_SOURCE_PATH} ..."
    # Eliminar cualquier contenido existente del directorio si existe.
    #
    # No solo usamos "rm -rf ${WORKSPACE_SOURCE_PATH}" porque ${WORKSPACE_SOURCE_PATH} podría ser "/"
    # o la raíz de un volumen montado.
    if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
      # Eliminar archivos y directorios no ocultos
      rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
      # Eliminar archivos y directorios que comienzan con . pero excluyendo ..
      rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
      # Eliminar archivos y directorios que comienzan con .. más cualquier otro carácter
      rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
    fi
