apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-and-cleanup-task
spec:
  workspaces:
    - name: source
  steps:
    # FRAGMENTO DE LA TAREA DE NOSE-TEST
    - name: run-nose-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install nose
        # pip install -r requirements.txt
        nosetests -v
        
    # FRAGMENTO DE LA TAREA DE LIMPIEZA
    - name: cleanup
      image: alpine:latest
      workingDir: $(workspaces.source.path)
      script: |
        echo "Ejecutando limpieza de archivos temporales..."
        rm -rf *.pyc __pycache__ .coverage
        echo "Limpieza completada."
